from .ResNet import ResNet152 as resnet152
from .ResNet import ResNet18 as resnet18
from .ResNet import ResNet20 as resnet20
from .ResNet import ResNet50 as resnet50
from .ResNet import ResNet56 as resnet56
from .ResNetAbsorbed import ResNet152 as resnet152a
from .ResNetAbsorbed import ResNet18 as resnet18a
from .ResNetAbsorbed import ResNet20 as resnet20a
from .ResNetAbsorbed import ResNet50 as resnet50a
from .ResNetAbsorbed import ResNet56 as resnet56a
